src/lib.rs

This gives better error messages in case of a mismatch.

tests: use assert_eq! instead of a simple assert!

---

Cargo.toml
benches/generate.rs
src/lib.rs

This introduces a lazily initialized static variable `LOREM_IPSUM_CHAIN` which is initialized the first time `lipsum` is called. This makes it much faster to generate lorem ipsum text using repeated calls to `lipsum` since the Markov chain is only trained once.

Use static Markov chain for lipsum calls

---

benches/learn.rs
src/lib.rs

This makes the `LOREM_IPSUM` and `LIBER_PRIMUS` constants public -- in case people want to use them from their own programs -- and proceeds to make a small benchmark for training a Markov chain on these variables. That way we can track the time for this and potentially optimize it later.

Add Markov chain learning benchmarks

---

src/lib.rs

Before we would always generate `n + 2` words. We now generate at least
two words, and no more than `n` words.

generate_from: generate at most n words

---

.travis.yml
src/lib.rs

With just a few changes, the code could be made compatible with Rust 1.6.0. This is nice since it allows me to use the lipsum crate from my textwrap crate.

Test with Rust 1.6.0 on TravisCI

---

.rustfmt.toml
benches/learn.rs

This configuration mostly matches the existing code style, which I
happen to like. Compared to the new style agreed upon in the RFC
process, this style uses more visual layouts.
With the struct_lit_width setting, small struct literals are put onto
a single line.

rustfmt: add config file

---

src/lib.rs

These methods return an iterator which will generate a neverending
chain of words. The iterator can be used by itself, or it can be used
indirectly by the generate and generate_from methods.
The new iterator works slightly differently from the old code in
corner cases where the iteration ends up in a state from which there
is no next state in the Markov chain. Like before, a new state is
picked at random, but this now happens one word earlier than before.
This should not make a big difference outside of artificially small
test cases.

MarkovChain: add iter and iter_from methods

---

Cargo.toml
src/lib.rs

The aim of this PR is to make it possible to customize the random number generator used by the Markov chains. If the RNG can be specified by the user, the user can ensure deterministic output, which is useful for testing.

Put the random number generator into the Markov chain

---

README.md
src/lib.rs

Before we would just put random words together in the `generate` method. The resulting sentence could easily begin with a lowercase word and end without a full-stop. We now take care to capitalize the first word and will add a `.` as necessary.

Generate full sentences

---

src/lib.rs

This is per C-HTML-ROOT in the Rust API Guidelines:
https://rust-lang-nursery.github.io/api-guidelines/documentation.html

lib: set html_root_url

---

.travis.yml
README.md

The rand crate bumped its minimum version with the 0.3.18 release.

travis: bump minimum supported Rust version to 1.8

---

.travis.yml
README.md

This allows us to upgrade to rand 0.4 and to remove a workaround for
testing with version-sync.

travis: bump minimum rustc version to 1.17.0

---

.rustfmt.toml
src/lib.rs

The new rustfmt from rustfmt-preview has changed the option names and
I guess the defaults are okay for us.

lib: format using rustfmt defaults

---

.circleci/config.yml
.travis.yml

This moves the coverage generation from Travis CI to CircleCI: we can
run up to four Docker containers at the same time there and they start
really fast.
So this means we can do more things in parallel by spreading the load
over two different CI providers.

circleci: generate coverage report

---

.travis.yml
Cargo.toml
README.md
src/lib.rs
tests/version-numbers.rs

As usual, this means that we now require a newer version of Rust, the minimum version jumped from 1.17 to 1.22.

Update all dependencies

---

.travis.yml
README.md

Version 1.22 is from 2017-11-22 and the build seems to fail with that version. I hope using Rust 2018 will be prove more stable going forward.

travis: bump minimum support version to Rust 2018

---

.circleci/config.yml

This way we can specify the necessary Docker security options to let
Tarpaulin run while still getting the benefits of using a prebuilt
Docker image.

Run cargo tarpaulin in a machine image

---

Cargo.toml

This version is still compatible with Rust 2018.

cargo: update version-sync to latest version

---

.travis.yml
Cargo.toml
README.md
benches/generate.rs
benches/learn.rs
examples/lipsum.rs
src/lib.rs
tests/version-numbers.rs

Repeated build failures makes it infeasible to keep lipsum compatible
with any particular version of Rust. We will therefore track the
latest stable version of Rust from now on.

Drop Rust 1.31 compatibility

---

src/lib.rs

The implementation has been stable for a while now, so we can remove
our copy.

lib: use char::is_ascii_punctuation

---

src/lib.rs

This fixes a typo and removes some unnecessary detail from the module
docstring.

lib: simplify module docstring

---

Cargo.toml
README.md
src/lib.rs

I noticed that I often need to generate a deterministic string of
random words in unit tests. This helper function does this.
Since we need a concrete RNG for this, `rand_chacha` is now an
explicit dependency of `lipsum`. We already had an indirect dependency
on this crate since `rand` pulls in `rand_chacha` by default.

Add lipsum_words_from_seed helper function

---

src/lib.rs

I guess this could also have been a doctest, Tarpaulin doesn't seem to
pick up the coverage from those.

Add a unit test for lipsum_words_from_seed

---

Cargo.toml
README.md
src/lib.rs

Split out RNG from MarkovChain to allow reusing a model multiple times.

---

src/lib.rs

Hey,
thanks for the nice library!
I'm considering using this in one of my projects to allow users to create blind text of arbitrary length. I'd prefer everyone to have the same output for a given length while preserving the iconic start "Lorem ipsum dolor sit amet". Hence, I needed a function combining the properties of `lipsum` and `lipsum_words_from_seed`. I added `lipsum_from_seed` (very easy thanks to great design!) for this purpose and rearranged both its and `lipsum_words_from_seed` doc string a bit as to not make the function overview to wordy.
While implementing the new function, I realized that `lipsum` will sometimes yield strings like `"Nullam habuit. voluptatem cum summum."` containing punctuation followed by non-capitalized words. This did not look very nice to me, so I …

Add `lipsum_from_seed` and tweak capitalization.

---

Cargo.toml

When trying to publish the 0.8.1 release, I found that the number of tags is limited to five on crates.io.

Remove some unnecessary crate tags

---

.github/workflows/build.yml

Strangely, the didn’t cause an error: instead the build would seemingly hang forever saying:
Requested labels: window-latest
Job defined at: mgeisler/lipsum/.github/workflows/build.yml@refs/pull/86/merge
Waiting for a runner to pick up this job...

Use the correct `windows-latest` OS name

---

README.md

Back in 2020, I gave up on trying to keep the library compatible with old Rust releases. This was with the 0.7.0 release which gave up compatibility with Rust 1.31 (the first version of the 2018 edition).
Since then, the releases have roughly tracked the latest stable release of Rust, with no particular urgency to bump this of course.
This is related to #83 where @WorldSEnder noticed that Lipsum no longer compiles on Rust 1.56. This was easy to fix (#84), but we should still remove the misleading badge.

Remove outdated Rust 1.31 badge

---

src/lib.rs

Something changed between Rust 1.57 and 1.58 so that the slice pattern doesn’t work without an explicit type annotation in the earlier version. Without it, we get
```
error[E0277]: expected a `Fn<(char,)>` closure, found `[char; 3]`
--> src/lib.rs:350:52
|
350 |             let mut needs_cap = sentence.ends_with(punctuation);
|                                                    ^^^^^^^^^^^ expected an `Fn<(char,)>` closure, found `[char; 3]`
|
= help: the trait `Fn<(char,)>` is not implemented for `[char; 3]`
= note: required because of the requirements on the impl of `FnOnce<(char,)>` for `&[char; 3]`
= note: required because of the requirements on the impl of `Pattern<'_>` for `&[char; 3]`
```
Between 1.57 and 1.58, the `Pattern` trait got a new implementation for `[char; N]`, and I …

Fix build error on Rust 1.56

---

.github/workflows/build.yml

This is the first version to support the 2021 edition. I tried tracking the minimum supported Rust version (MSRV) back in 2020, but this turned out to be infeasible because of frequent bumps to the MSRV in our dependencies (see https://github.com/mgeisler/lipsum/commit/9d622ccd23ec0b2ae258270e244cd171290b057d). I hope the update pace has cooled enough to make the feasible again.
I plan to (conservatively) bump this version up as needed going forward. This will of course announcing it in the release notes of new releases.
See https://github.com/mgeisler/lipsum/issues/83 for the motivation.

Test minimum supported Rust version (Rust 1.56) in CI

---

Cargo.toml
src/lib.rs

As discussed in #74, here is a PR that makes system randomness an optional (but enabled by default) feature.
The catch of this PR is that it interacts badly with the test for the example. `cargo build --no-default-features` works as intended, but `cargo test --no-default-features` will fail unless the code in the main function of `examples/lipsum.rs` is removed. Furthermore, I had to adapt one documentation example such that it would work without `thread_rng`. There are [methods to exclude examples from doctesting depending on the features the crate is built with,](https://users.rust-lang.org/t/doctests-that-require-a-non-default-feature-is-it-possible/29529/4) but they are ugly.
I'd be happy to incorporate any feedback on naming / test architecture. Have a nice day!

Add `getrandom` feature

---

.github/workflows/build.yml
Cargo.toml

- byteorder v1.5.0 requires 1.60
- ppv-lite86 v0.2.20 requires 1.61

Bump MSRV to 1.61 to accommodate our dependencies
